name: Run XYZsports M3U8 Builder

# Workflow ne zaman çalışsın
on:
  push:
    branches:
      - main
  workflow_dispatch: # Manuel tetikleme için

jobs:
  build-m3u8:
    runs-on: ubuntu-latest

    steps:
      # Repo'yu klonla
      - name: Checkout repository
        uses: actions/checkout@v3

      # Python kur
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Gerekli paketleri yükle
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx

      # Scripti çalıştır
      - name: Run XYZsports script
        run: |
          python xyzsports.py

      # Oluşan m3u dosyasını artifact olarak sakla
      - name: Upload M3U8 artifact
        uses: actions/upload-artifact@v4
        with:
          name: xyzvt-m3u
          path: xyzvt.m3u
