# .github/workflows/run_xyzsports.yml
name: Run XYZsports M3U8 Builder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "httpx[http2]"

      - name: Run XYZsports script
        run: |
          python xyzsports.py

      - name: Upload M3U8 artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xyzvt-m3u
          path: xyzvt.m3u
          if-no-files-found: warn
